name: pybsp
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - shapely=1.7.1=py38h210f175_0
  - networkx=2.6.1
  - tqdm
  - stonesoup
  - numpy=1.20.3
  - pyshp
  - matplotlib=3.4.2
  - geopandas=0.9.0=py_1